// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package types holds the data model shared by the probe, the aggregator and
the frontend. Everything here is part of a wire format: IngestPayload is the
probe protocol, Overall and IncidentHistory are public API responses.
*/

export const StatusOK = "ok";
export const StatusDegraded = "degraded";
export const StatusDown = "down";
export type Status = typeof StatusOK | typeof StatusDegraded | typeof StatusDown;
export const KindGuest = "guest";
export const KindAuth = "auth";
export type Kind = typeof KindGuest | typeof KindAuth;
/**
 * Result is one probe observation.
 */
export interface Result {
  ts: number /* int64 */;
  probe: string;
  region: string;
  domain: string;
  kind: Kind;
  status: Status;
  latency_ms: number /* int */;
  http_code?: number /* int */;
  err?: string;
}
/**
 * IngestPayload is the body a probe POSTs to /api/ingest.
 */
export interface IngestPayload {
  probe: string;
  region: string;
  results: Result[];
  online_count?: number /* int */; // bangumi.tv signed-in "online: N" badge
  online_ts?: number /* int64 */;
}
/**
 * OnlinePoint is one sample of a (ts, value) series.
 * For raw (per-minute) series Count is the sampled value and Low/Peak are
 * omitted. For bucketed series Count is the per-bucket average (the trend),
 * while Low/Peak are the bucket's min/max so the chart can draw a range band
 * around the trend line — a single spiky minute lifts Peak without distorting
 * the average.
 */
export interface OnlinePoint {
  ts: number /* int64 */;
  count: number /* int */;
  low?: number /* int */;
  peak?: number /* int */;
}
/**
 * WikiStatsPoint is one daily row scraped from chii.in/wiki/stats.
 */
export interface WikiStatsPoint {
  title: string;
  date: string;
  timestamp: number /* int64 */;
  register_total: number /* int */;
  collection_total: number /* int */;
  topic_total: number /* int */;
  reply_total: number /* int */;
  collection_1: number /* int */;
  collection_2: number /* int */;
  collection_3: number /* int */;
  collection_4: number /* int */;
  collection_5: number /* int */;
  topic_1: number /* int */;
  topic_2: number /* int */;
  topic_7: number /* int */;
  reply_1: number /* int */;
  reply_2: number /* int */;
  reply_3: number /* int */;
  reply_4: number /* int */;
  reply_5: number /* int */;
  reply_6: number /* int */;
  reply_7: number /* int */;
  reply_8: number /* int */;
}
/**
 * Component is a (domain, kind) pair shown as one row in the UI.
 */
export interface Component {
  domain: string;
  kind: Kind;
  label: string;
}
/**
 * ComponentKey identifies one monitored (domain, kind) pair.
 */
export interface ComponentKey {
  Domain: string;
  Kind: Kind;
}
/**
 * DayBucket is a single daily uptime cell (used in 30-day strip).
 */
export interface DayBucket {
  day: string; // YYYY-MM-DD (CST)
  uptime: number /* float64 */;
  total: number /* int */;
  down: number /* int */;
  degrade: number /* int */;
  status: Status; // summary status for the day
}
export interface ComponentStatus {
  domain: string;
  kind: Kind;
  label: string;
  status: Status; // current rolled-up status
  uptime: number /* float64 */; // 0-100
  since?: number /* int64 */; // unix seconds the current non-ok state began (0 when ok)
  days: DayBucket[]; // 30 entries, oldest first
  last_check: number /* int64 */; // unix seconds
  probe_views: ProbeView[]; // per-probe latest status
  incidents?: Incident[]; // recent incident windows (≤14d)
}
/**
 * Incident is a contiguous window where the rolled-up status was not ok.
 */
export interface Incident {
  start_ts: number /* int64 */;
  end_ts: number /* int64 */;
  status: Status; // worst status during the window
  duration_s: number /* int */;
  peak_down: number /* int */; // max probes reporting down
  peak_total: number /* int */; // active probes at peak
}
/**
 * HistoryIncident is an Incident annotated with the component it belongs to.
 * The standalone history page lists incidents across all components at once, so
 * unlike ComponentStatus.Incidents each entry has to name its own component.
 */
export interface HistoryIncident extends Incident {
  domain: string;
  kind: Kind;
  label: string;
}
/**
 * IncidentHistory is the /api/incidents body: one page of archived incidents
 * plus the bounds the frontend needs to page further back.
 */
export interface IncidentHistory {
  incidents: HistoryIncident[]; // newest first
  from: number /* int64 */; // window start (unix seconds, inclusive)
  to: number /* int64 */; // window end (unix seconds, exclusive)
  earliest_ts?: number /* int64 */;
}
export interface ProbeView {
  probe: string;
  region: string;
  status: Status;
  latency_ms: number /* int */;
  http_code?: number /* int */;
  ts: number /* int64 */;
  err?: string;
}
export interface Probe {
  name: string;
  region: string;
  last_seen: number /* int64 */;
  online: boolean;
}
export interface Overall {
  status: Status;
  message: string;
  updated_at: number /* int64 */;
  components: ComponentStatus[];
  probes: Probe[];
  online?: OnlinePoint[];
}
/**
 * ReactionCount is an aggregated count for one emoji over the active window.
 */
export interface ReactionCount {
  emoji_id: number /* int */;
  count: number /* int */;
  mine: boolean;
}
